# Generated by Django 4.0.3 on 2022-04-18 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('APP', '0002_remove_women_cat_delete_category_delete_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)], verbose_name='N')),
                ('M', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)], verbose_name='M')),
                ('result', models.IntegerField(default=None, verbose_name='Результат')),
            ],
        ),
        migrations.CreateModel(
            name='MatrixB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)], verbose_name='N')),
                ('M', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(2)], verbose_name='M')),
                ('result', models.IntegerField(default=None, verbose_name='Результат')),
            ],
        ),
    ]
