# Generated by Django 4.0.3 on 2022-04-18 07:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matrixa',
            name='M',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='matrixa',
            name='N',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='N'),
        ),
        migrations.AlterField(
            model_name='matrixb',
            name='M',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='M'),
        ),
        migrations.AlterField(
            model_name='matrixb',
            name='N',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)], verbose_name='N'),
        ),
    ]
